language: java
jdk: openjdk8
notifications: 
email: pforsthoff@gmail.com
cache: npm

before_install:
install: true
before_script:
script:
  - ./gradlew build --scan -s --warning-mode=all
after_success:
after_failure:
after_script:
before_deploy:
deploy:
provider: releases
skip_cleanup: true
github-token: $GITHUB_TOKEN
on:
  branch: master
after_deploy:
