language: java
jdk: openjdk8
notifications: 
email: pforsthoff@gmail.com
cache: npm
env:
  global:
    - CF_API_URL: https://Api.run.pivotal.io
  
before_install:
install: true
before_script:
script:
  - ./gradlew build --warning-mode=all
after_success:
after_failure:
after_script:
before_deploy:
deploy:
 	provider: cloudfoundry
 	api: $CF_API_URL
 	username: $CF_USERNAME
 	password: $CF_PASSWORD
 	organization: $CF_ORG
 	space: $CF_SPACE

provider: releases
skip_cleanup: true
github-token: $GITHUB_TOKEN
on:
  branch: master
after_deploy:
